/**
 * Dancing stickers, generated by `scripts/fetch-dances.mjs` into dances.json.
 * Hand edits there get overwritten; change the `dance` seed in countries.ts or
 * the queries in the script instead.
 *
 * Empty until someone runs `npm run dances` with a Giphy key, and the reveal
 * simply renders no dancers until then.
 */
import data from "./dances.json";

export type Dance = {
  id: string;
  title: string;
  /** Animated frame: WebP where Giphy has one, so the alpha edges stay clean. */
  src: string;
  /** Single frame, shown instead of the animation under reduced motion. */
  still: string;
  width: number;
  height: number;
  pageUrl: string;
  /** False for a pinned GIF: solid background rather than a cut-out. */
  transparent: boolean;
};

type DanceData = {
  pool: Dance[];
  byCountry: Record<string, Dance>;
  /** Only the countries that pin their right-hand partner; absent before the
   *  script grew that half, hence the default below. */
  rightByCountry?: Record<string, Dance>;
};

const { pool: POOL, byCountry: BY_COUNTRY, rightByCountry: RIGHT_BY_COUNTRY = {} } = data as DanceData;

export const hasDances = POOL.length >= 2;
export { POOL, BY_COUNTRY, RIGHT_BY_COUNTRY };

/** FNV-1a. Small, stable, and no dependency — this only has to spread evenly. */
function hash(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * The pair flanking a country: its own sticker on the left, one from the
 * shared meme pool on the right.
 *
 * Both are derived from the country code rather than drawn at random, so a
 * guest sees the same dancers on every reload — and so the server and client
 * agree on what to render, which `Math.random()` would not.
 *
 * A country with no sticker of its own falls back to a second pool pick,
 * stepped so it can never collide with the right-hand one.
 *
 * A country that pins its partner overrides the pool draw on the right. The
 * draw is still made, because the left-hand fallback is stepped off it — so
 * pinning a partner never changes which sticker a different country gets.
 *
 * `rightIsPinned` says which of the two happened, because it decides whether
 * the right-hand one may be mirrored — see `Dancer`.
 */
export function getDancers(
  code: string,
): { left: Dance; right: Dance; rightIsPinned: boolean } | null {
  if (!hasDances) return null;
  const h = hash(code);
  const rightIndex = h % POOL.length;
  const step = 1 + (Math.floor(h / POOL.length) % (POOL.length - 1));
  const pinned = RIGHT_BY_COUNTRY[code];
  return {
    left: BY_COUNTRY[code] ?? POOL[(rightIndex + step) % POOL.length],
    right: pinned ?? POOL[rightIndex],
    rightIsPinned: Boolean(pinned),
  };
}

/**
 * One specific sticker, by Giphy id. For a page that pins its own dancer
 * rather than deriving a pair from a country code.
 *
 * Only the pool is searched: an id worth pinning belongs in `MUST_HAVE` in
 * `scripts/fetch-dances.mjs`, which is what puts it there and keeps it there
 * across a top-up.
 */
export function getDance(id: string): Dance | null {
  return POOL.find((d) => d.id === id) ?? null;
}
