/**
 * Transparent dancing stickers, generated by `scripts/fetch-dances.mjs` into
 * dances.json. Hand edits there get overwritten; change the queries in the
 * script instead.
 *
 * Empty until someone runs `npm run dances` with a Giphy key, and the reveal
 * simply renders no dancers until then.
 */
import dances from "./dances.json";

export type Dance = {
  id: string;
  title: string;
  /** Animated frame: WebP where Giphy has one, so the alpha edges stay clean. */
  src: string;
  /** Single frame, shown instead of the animation under reduced motion. */
  still: string;
  width: number;
  height: number;
  pageUrl: string;
};

const DANCES: Dance[] = dances;

export const hasDances = DANCES.length >= 2;

/** FNV-1a. Small, stable, and no dependency — this only has to spread evenly. */
function hash(text: string): number {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * The two dancers flanking a country. Derived from the code rather than picked
 * at random, so a guest sees the same pair every time they reload — and so the
 * server and client agree, which `Math.random()` would not.
 *
 * The second index is offset by at least one, so the two sides can never land
 * on the same sticker.
 */
export function getDancers(code: string): [Dance, Dance] | null {
  if (!hasDances) return null;
  const h = hash(code);
  const first = h % DANCES.length;
  const step = 1 + (Math.floor(h / DANCES.length) % (DANCES.length - 1));
  return [DANCES[first], DANCES[(first + step) % DANCES.length]];
}
