/**
 * Resolved song previews, keyed by country code. Generated by
 * `scripts/fetch-songs.mjs` into songs.json — hand edits there get
 * overwritten; change the `song` seed in countries.ts instead.
 *
 * `previewUrl` points at Apple's CDN and is played from there, never
 * re-hosted: their previews are licensed for playback alongside a link back
 * to the store, which is what `trackUrl` is for.
 */
import songs from "./songs.json";

export type Song = {
  title: string;
  artist: string;
  /** 30s AAC preview on Apple's CDN. ~1 MB, CORS-open, no auth. */
  previewUrl: string;
  /** Store page. Rendered as the attribution link the preview terms require. */
  trackUrl: string;
  artwork: string;
};

const SONGS: Record<string, Song> = songs;

/** Undefined for the countries whose anthem is the point (USA, France). */
export function getSong(code: string): Song | undefined {
  return SONGS[code];
}
